version: '3'
services:
    meecha:
        image: golang:1.20.13-bullseye
        volumes:
            - ./meecha:/root/meecha
        tty: true
        restart: always
        depends_on:
            - redis
            - postgresql
        working_dir: /root/meecha

    redis:
        image: "redis:latest"
        ports:
            - "26379:6379"
            
    postgresql:
        image: postgres:12.18-bullseye
        environment:
            - TZ=Asia/Tokyo
        ports:
            - "25432:5432"
        env_file:
            - .env
        volumes:
            - ./postgresql:/var/lib/postgresql/data

    meecha_nginx:
        restart: always
        image: nginx:latest
        container_name: meecha_nginx
        ports:
            - "8443:80"
        volumes:
            # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics:/etc/nginx/static/statics
        tty: true