version: '3'
services:
    meecha:
        image: golang:1.20.13-bullseye
        ports:
            - 12222:12222
        volumes:
            - ./meecha:/root/meecha
        tty: true
        restart: always
        depends_on:
            - redis
            - postgresql
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
    postgresql:
        image: postgres:12.18-bullseye
        environment:
            - TZ=Asia/Tokyo
        ports:
            - "15432:5432"
        env_file:
            - .env
        volumes:
            - ./postgresql:/var/lib/postgresql/data