version: '3'
services:
    meecha:
        image: golang:1.20.13-bullseye
        ports:
            - 12222:12222
        volumes:
            - ./meecha:/root/meecha
        tty: true
        restart: always
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./redis:/data"